# Generated by Django 4.2.29 on 2026-04-20 00:38

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cpf_cnpj', models.CharField(max_length=20)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('cep', models.CharField(blank=True, max_length=10, null=True)),
                ('logradouro', models.CharField(blank=True, max_length=255, null=True)),
                ('numero', models.CharField(blank=True, max_length=20, null=True)),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, max_length=2, null=True)),
                ('contato_whatsapp', models.BooleanField(default=False)),
                ('contato_email', models.BooleanField(default=False)),
                ('contato_sms', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cliente',
            },
        ),
        migrations.CreateModel(
            name='Oficina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cnpj', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('especialidade', models.CharField(blank=True, choices=[('geral', 'Mecânica Geral'), ('eletrica', 'Elétrica'), ('funilaria', 'Funilaria e Pintura')], max_length=100, null=True)),
                ('horario_abertura', models.TimeField(blank=True, null=True)),
                ('horario_fechamento', models.TimeField(blank=True, null=True)),
                ('dias_funcionamento', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('seg', 'Segunda-feira'), ('ter', 'Terça-feira'), ('qua', 'Quarta-feira'), ('qui', 'Quinta-feira'), ('sex', 'Sexta-feira'), ('sab', 'Sábado'), ('dom', 'Domingo')], max_length=3), blank=True, default=list, null=True, size=None)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos_oficina/')),
                ('cep', models.CharField(blank=True, max_length=10, null=True)),
                ('logradouro', models.CharField(blank=True, max_length=255, null=True)),
                ('numero', models.CharField(blank=True, max_length=20, null=True)),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, max_length=2, null=True)),
                ('plano_atual', models.CharField(choices=[('basico', 'Básico'), ('premium', 'Premium')], default='basico', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Oficina',
                'db_table': 'oficina',
            },
        ),
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('execucao', 'Em Execução'), ('concluido', 'Concluído')], default='pendente', max_length=20)),
                ('km_atual', models.IntegerField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordens_servico', to='modulo_oficina.cliente')),
                ('oficina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordens_servico', to='modulo_oficina.oficina')),
            ],
            options={
                'db_table': 'ordem_servico',
            },
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10)),
                ('marca', models.CharField(blank=True, max_length=100, null=True)),
                ('modelo', models.CharField(max_length=100)),
                ('ano', models.CharField(blank=True, max_length=4, null=True)),
                ('cor', models.CharField(blank=True, max_length=50, null=True)),
                ('chassi', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo_uso', models.CharField(choices=[('particular', 'Particular'), ('comercial', 'Comercial/Frota')], default='particular', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='veiculos', to='modulo_oficina.cliente')),
            ],
            options={
                'db_table': 'veiculo',
            },
        ),
        migrations.CreateModel(
            name='TarefaExecucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('execucao', 'Em Execução'), ('concluido', 'Concluído')], default='pendente', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('os', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='modulo_oficina.ordemservico')),
            ],
            options={
                'db_table': 'tarefa_execucao',
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('tempo_estimado', models.DecimalField(decimal_places=2, max_digits=5)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('oficina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalogo_servicos', to='modulo_oficina.oficina')),
            ],
            options={
                'db_table': 'servico',
            },
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordens_servico', to='modulo_oficina.veiculo'),
        ),
        migrations.CreateModel(
            name='ItemOrcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('peca', 'Peça'), ('servico', 'Serviço')], max_length=10)),
                ('nome_descricao', models.CharField(max_length=255)),
                ('quantidade', models.IntegerField(default=1)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categoria_veiculo', models.CharField(blank=True, max_length=50, null=True)),
                ('status_aprovacao', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('reprovado', 'Reprovado')], default='pendente', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('os', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_orcamento', to='modulo_oficina.ordemservico')),
                ('servico_catalogo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='modulo_oficina.servico')),
            ],
            options={
                'db_table': 'item_orcamento',
            },
        ),
        migrations.CreateModel(
            name='HistoricoOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('criacao', 'Criação'), ('checklist', 'Checklist'), ('diagnostico', 'Diagnóstico'), ('aprovacao', 'Aprovação'), ('execucao', 'Execução'), ('conclusao', 'Conclusão'), ('status', 'Mudança de Status'), ('default', 'Outros')], default='default', max_length=20)),
                ('descricao', models.CharField(max_length=255)),
                ('detalhes', models.TextField(blank=True, null=True)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('os', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='modulo_oficina.ordemservico')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historicos_os', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'historico_os',
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='documentos_os/')),
                ('nome_arquivo', models.CharField(blank=True, max_length=255, null=True)),
                ('origem', models.CharField(choices=[('checklist', 'Checklist Inicial'), ('geral', 'Anexo Geral (NF, Orçamento)')], default='geral', max_length=20)),
                ('categoria', models.CharField(blank=True, choices=[('externo', 'Parte Externa'), ('interno', 'Parte Interna'), ('mecanica', 'Mecânica')], max_length=20, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('os', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='modulo_oficina.ordemservico')),
            ],
            options={
                'db_table': 'documentos',
            },
        ),
        migrations.CreateModel(
            name='ConfigPreco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_hora_mecanico', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('percentual_popular', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('percentual_eletrico', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('percentual_luxo', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('percentual_esportivo', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('percentual_utilitario', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('percentual_minivan', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('oficina', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config_preco', to='modulo_oficina.oficina')),
            ],
            options={
                'db_table': 'config_preco',
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='oficina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='modulo_oficina.oficina'),
        ),
        migrations.CreateModel(
            name='ChecklistRecebimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concluido', models.BooleanField(default=False)),
                ('data_recebimento', models.DateField(blank=True, null=True)),
                ('consultor', models.CharField(blank=True, max_length=255, null=True)),
                ('nivel_combustivel', models.CharField(blank=True, choices=[('reserva', 'Reserva'), ('1/4', '1/4'), ('1/2', '1/2 (Meio Tanque)'), ('3/4', '3/4'), ('cheio', 'Cheio')], max_length=20, null=True)),
                ('observacoes_iniciais', models.TextField(blank=True, null=True)),
                ('lataria_pintura', models.TextField(blank=True, null=True)),
                ('vidros_farois', models.TextField(blank=True, null=True)),
                ('possui_manual', models.BooleanField(default=False)),
                ('possui_estepe_macaco', models.BooleanField(default=False)),
                ('observacoes_internas', models.TextField(blank=True, null=True)),
                ('nivel_oleo', models.CharField(choices=[('ok', 'Nível Normal'), ('low', 'Baixo'), ('crit', 'Crítico/Vazio')], default='ok', max_length=20)),
                ('fluido_arrefecimento', models.CharField(choices=[('ok', 'Nível Normal'), ('low', 'Baixo')], default='ok', max_length=20)),
                ('observacoes_mecanica', models.TextField(blank=True, null=True)),
                ('assinatura_cliente', models.TextField(blank=True, null=True)),
                ('assinatura_tecnico', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('os', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='modulo_oficina.ordemservico')),
            ],
            options={
                'db_table': 'checklist_recebimento',
            },
        ),
        migrations.AlterUniqueTogether(
            name='cliente',
            unique_together={('oficina', 'cpf_cnpj')},
        ),
    ]
