# Generated by Django 6.0.2 on 2026-03-29 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistRecebimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concluido', models.BooleanField(blank=True, null=True)),
                ('assinatura_cliente', models.TextField(blank=True, null=True)),
                ('assinatura_tecnico', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'checklist_recebimento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentoOs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('arquivo', models.CharField(max_length=500)),
                ('enviado_em', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'documento_os',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FotoChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.CharField(max_length=500)),
                ('criado_em', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'foto_checklist',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ItemOrcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=10, null=True)),
                ('nome_descricao', models.CharField(max_length=255)),
                ('quantidade', models.IntegerField(blank=True, null=True)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dificuldade', models.CharField(blank=True, max_length=50, null=True)),
                ('status_aprovacao', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'item_orcamento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('km_atual', models.IntegerField()),
                ('criado_em', models.DateTimeField(blank=True, null=True)),
                ('atualizado_em', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ordem_servico',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('modelo', models.CharField(max_length=100)),
                ('ano', models.IntegerField(blank=True, null=True)),
                ('cor', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'veiculo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CategoriaVeiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('percentual', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('icone', models.CharField(blank=True, default='fa-car', max_length=50)),
                ('cor', models.CharField(blank=True, default='#22c55e', max_length=20)),
            ],
            options={
                'verbose_name': 'Categoria de Veículo',
                'verbose_name_plural': 'Categorias de Veículos',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_index=True, max_length=255)),
                ('documento', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('telefone', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=255)),
                ('cep', models.CharField(blank=True, default='', max_length=10)),
                ('logradouro', models.CharField(blank=True, default='', max_length=255)),
                ('numero', models.CharField(blank=True, default='', max_length=20)),
                ('complemento', models.CharField(blank=True, default='', max_length=100)),
                ('bairro', models.CharField(blank=True, default='', max_length=100)),
                ('cidade', models.CharField(blank=True, default='', max_length=100)),
                ('estado', models.CharField(blank=True, default='', max_length=2)),
                ('preferencias', models.JSONField(blank=True, default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True, null=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cliente',
                'ordering': ['-criado_em'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoOficina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_hora', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração da Oficina',
                'verbose_name_plural': 'Configurações da Oficina',
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('tempo', models.DecimalField(decimal_places=2, help_text='Horas estimadas', max_digits=5)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='documentos/os_%Y/%m/')),
                ('nome', models.CharField(max_length=255)),
                ('tipo', models.CharField(blank=True, max_length=50)),
                ('data_inclusao', models.DateTimeField(auto_now_add=True)),
                ('os', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='modulo_oficina.ordemservico')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('criacao', 'Criação'), ('checklist', 'Checklist'), ('diagnostico', 'Diagnóstico'), ('aprovacao', 'Aprovação'), ('execucao', 'Execução'), ('conclusao', 'Conclusão'), ('status', 'Mudança de Status'), ('default', 'Geral')], default='default', max_length=20)),
                ('descricao', models.CharField(max_length=255)),
                ('detalhes', models.TextField(blank=True, null=True)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('os', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='modulo_oficina.ordemservico')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'historico_os',
                'ordering': ['-data_hora'],
            },
        ),
        migrations.CreateModel(
            name='TarefaExecucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_execucao', 'Em Execução'), ('concluido', 'Concluído')], default='pendente', max_length=20)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('os', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='modulo_oficina.ordemservico')),
            ],
        ),
    ]
