# Generated by Django 4.2.29 on 2026-05-02 01:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('modulo_oficina', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permissao', models.CharField(choices=[('admin', 'Administrador'), ('gerente', 'Gerente'), ('mecanico', 'Mecânico'), ('atendente', 'Atendente'), ('visualizador', 'Visualizador')], default='visualizador', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('oficina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funcionarios', to='modulo_oficina.oficina')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='funcionario_oficina', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'funcionario',
                'unique_together': {('oficina', 'user')},
            },
        ),
    ]
