# Generated by Django 6.0.2 on 2026-03-22 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_oficina', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaVeiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('percentual', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('icone', models.CharField(blank=True, default='fa-car', max_length=50)),
                ('cor', models.CharField(blank=True, default='#22c55e', max_length=20)),
            ],
            options={
                'verbose_name': 'Categoria de Veículo',
                'verbose_name_plural': 'Categorias de Veículos',
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoOficina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_hora', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração da Oficina',
                'verbose_name_plural': 'Configurações da Oficina',
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('tempo', models.DecimalField(decimal_places=2, help_text='Horas estimadas', max_digits=5)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
            },
        ),
    ]
