# Generated by Django 4.2.29 on 2026-05-14 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_oficina', '0002_funcionario'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManutencaoPreventiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('descricao', models.TextField(blank=True)),
                ('periodicidade', models.CharField(choices=[('km', 'Por quilometragem'), ('tempo', 'Por tempo'), ('ambos', 'Quilometragem ou tempo')], default='ambos', max_length=10)),
                ('intervalo_km', models.IntegerField(blank=True, null=True)),
                ('intervalo_meses', models.IntegerField(blank=True, null=True)),
                ('km_proxima', models.IntegerField(blank=True, null=True)),
                ('data_proxima', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('agendado', 'Agendado'), ('realizado', 'Realizado'), ('vencido', 'Vencido')], default='pendente', max_length=20)),
                ('ultima_revisao_em', models.DateField(blank=True, null=True)),
                ('ultima_revisao_km', models.IntegerField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('os_gerada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manutencoes_origem', to='modulo_oficina.ordemservico')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manutencoes_preventivas', to='modulo_oficina.veiculo')),
            ],
            options={
                'db_table': 'manutencao_preventiva',
                'ordering': ('data_proxima', 'km_proxima'),
                'indexes': [models.Index(fields=['veiculo', 'status'], name='manutencao__veiculo_3f29b2_idx')],
            },
        ),
    ]
