# Generated by Django 4.2.29 on 2026-05-16 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_oficina', '0003_manutencaopreventiva'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='preco_sugerido',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Preço sugerido (R$) usado como sugestão no orçamento.', max_digits=10),
        ),
        migrations.AddField(
            model_name='tarefaexecucao',
            name='concluida_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tarefaexecucao',
            name='iniciada_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tarefaexecucao',
            name='responsaveis',
            field=models.ManyToManyField(blank=True, help_text='Funcionários responsáveis pela execução desta tarefa.', related_name='tarefas_atribuidas', to='modulo_oficina.funcionario'),
        ),
        migrations.AddField(
            model_name='tarefaexecucao',
            name='tempo_estimado_h',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Tempo estimado em horas.', max_digits=5),
        ),
        migrations.AddField(
            model_name='tarefaexecucao',
            name='tempo_gasto_minutos',
            field=models.PositiveIntegerField(default=0, help_text='Tempo gasto real em minutos. Calculado quando a tarefa é concluída.'),
        ),
        migrations.CreateModel(
            name='ServicoTarefaPadrao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('ordem', models.PositiveSmallIntegerField(default=0, help_text='Ordem de exibição/execução dentro do serviço.')),
                ('tempo_estimado_h', models.DecimalField(decimal_places=2, default=0, help_text='Tempo estimado em horas para esta tarefa.', max_digits=5)),
                ('obrigatoria', models.BooleanField(default=True, help_text='Quando True, marca o checklist como obrigatório.')),
                ('ativa', models.BooleanField(default=True, help_text='Quando False, deixa de ser usada para popular novas OS.')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas_padrao', to='modulo_oficina.servico')),
            ],
            options={
                'db_table': 'servico_tarefa_padrao',
                'ordering': ('servico', 'ordem', 'id'),
                'indexes': [models.Index(fields=['servico', 'ordem'], name='servico_tar_servico_11c2ad_idx')],
            },
        ),
    ]
