# Generated by Django 4.2.29 on 2026-05-16 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_oficina', '0004_execucao_tarefas_padrao'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaVeiculoCustom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('percentual', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('icone', models.CharField(default='fa-circle-plus', help_text='Classe Font Awesome (ex: "fa-tractor", "fa-motorcycle").', max_length=40)),
                ('cor', models.CharField(default='#64748b', help_text='Cor hex usada para o card no painel de preços.', max_length=20)),
                ('ativa', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('oficina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias_custom', to='modulo_oficina.oficina')),
            ],
            options={
                'db_table': 'categoria_veiculo_custom',
                'ordering': ('nome',),
                'unique_together': {('oficina', 'nome')},
            },
        ),
    ]
