# Generated by Django 4.2.29 on 2026-05-16 07:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('modulo_oficina', '0005_categoria_custom'),
    ]

    operations = [
        migrations.CreateModel(
            name='OficinaLimitesOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limite_usuarios', models.PositiveIntegerField(blank=True, help_text='Sobrescreve `limite_usuarios_<plano>` para esta oficina.', null=True)),
                ('limite_os_mensal', models.PositiveIntegerField(blank=True, help_text='Sobrescreve `limite_os_mensal_<plano>` para esta oficina.', null=True)),
                ('limite_storage_mb', models.PositiveIntegerField(blank=True, help_text='Sobrescreve `limite_storage_mb_<plano>` para esta oficina.', null=True)),
                ('motivo', models.CharField(blank=True, help_text="Justificativa para auditoria (ex.: 'piloto comercial', 'TCC').", max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overrides_oficina', to=settings.AUTH_USER_MODEL)),
                ('oficina', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='limites_override', to='modulo_oficina.oficina')),
            ],
            options={
                'db_table': 'oficina_limites_override',
            },
        ),
    ]
