# Generated by Django 4.2.29 on 2026-05-13 01:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoGlobal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(max_length=80, unique=True)),
                ('valor', models.JSONField(blank=True, null=True)),
                ('descricao', models.CharField(blank=True, max_length=255)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuracoes_atualizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'adm_configuracao_global',
                'ordering': ('chave',),
            },
        ),
        migrations.CreateModel(
            name='AuditoriaLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('info', 'Informativo'), ('warning', 'Atenção'), ('critico', 'Crítico')], default='info', max_length=10)),
                ('acao', models.CharField(max_length=80)),
                ('recurso', models.CharField(blank=True, max_length=60)),
                ('recurso_id', models.CharField(blank=True, max_length=40)),
                ('descricao', models.CharField(max_length=255)),
                ('metadados', models.JSONField(blank=True, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias_admin', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'adm_auditoria_log',
                'ordering': ('-criado_em',),
                'indexes': [models.Index(fields=['-criado_em'], name='adm_auditor_criado__d25524_idx'), models.Index(fields=['acao'], name='adm_auditor_acao_77ef81_idx'), models.Index(fields=['recurso', 'recurso_id'], name='adm_auditor_recurso_3cf36d_idx')],
            },
        ),
    ]
