# Generated by Django 4.2.29 on 2026-05-14 23:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('modulo_adm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('acesso_cliente', 'Acesso de cliente à OS'), ('reset_senha', 'Pedido de redefinição de senha'), ('os_aprovada', 'OS aprovada pelo cliente'), ('os_rejeitada', 'Item rejeitado pelo cliente'), ('backup', 'Backup do banco'), ('oficina_inativada', 'Oficina inativada'), ('info', 'Informativo')], default='info', max_length=30)),
                ('nivel', models.CharField(choices=[('info', 'Informativo'), ('warning', 'Atenção'), ('critico', 'Crítico')], default='info', max_length=10)),
                ('titulo', models.CharField(max_length=160)),
                ('mensagem', models.TextField(blank=True)),
                ('link', models.CharField(blank=True, max_length=255)),
                ('metadados', models.JSONField(blank=True, null=True)),
                ('lida', models.BooleanField(default=False)),
                ('lida_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('destinatario', models.ForeignKey(blank=True, help_text='Quando informado, a notificação aparece apenas para esse usuário. Caso contrário, é visível para todos os staff/superuser.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes_admin', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'adm_notificacao',
                'ordering': ('-criado_em',),
                'indexes': [models.Index(fields=['-criado_em'], name='adm_notific_criado__75a567_idx'), models.Index(fields=['lida'], name='adm_notific_lida_340b71_idx'), models.Index(fields=['destinatario', '-criado_em'], name='adm_notific_destina_7dbcb2_idx')],
            },
        ),
    ]
