# Generated by Django 4.2.29 on 2026-05-16 01:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('modulo_adm', '0003_notificacao_tipos_recuperacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoErroProducao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(db_index=True, max_length=32, unique=True)),
                ('titulo', models.CharField(help_text="Resumo curto e amigável do erro ('Falha ao gerar boleto', etc.)", max_length=255)),
                ('mensagem_tecnica', models.TextField(help_text='Mensagem original da exceção. Usada para debug.')),
                ('tipo_excecao', models.CharField(blank=True, db_index=True, max_length=120)),
                ('endpoint', models.CharField(blank=True, db_index=True, max_length=255)),
                ('metodo_http', models.CharField(blank=True, max_length=10)),
                ('servico', models.CharField(blank=True, db_index=True, help_text="Componente lógico (ex.: 'modulo_oficina', 'auth', 'boletos').", max_length=80)),
                ('severidade', models.CharField(choices=[('info', 'Informativo'), ('warning', 'Atenção'), ('error', 'Erro'), ('critical', 'Crítico')], default='error', max_length=10)),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('monitorando', 'Monitorando'), ('silenciado', 'Silenciado'), ('resolvido', 'Resolvido')], db_index=True, default='aberto', max_length=12)),
                ('ambiente', models.CharField(blank=True, default='producao', help_text='producao | homologacao | desenvolvimento', max_length=20)),
                ('total_eventos', models.PositiveIntegerField(default=0)),
                ('usuarios_afetados', models.PositiveIntegerField(default=0)),
                ('primeira_ocorrencia', models.DateTimeField(default=django.utils.timezone.now)),
                ('ultima_ocorrencia', models.DateTimeField(default=django.utils.timezone.now)),
                ('silenciado_ate', models.DateTimeField(blank=True, null=True)),
                ('resolvido_em', models.DateTimeField(blank=True, null=True)),
                ('versao_app', models.CharField(blank=True, max_length=50)),
                ('metadados', models.JSONField(blank=True, null=True)),
                ('resolvido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grupos_erro_resolvidos', to=settings.AUTH_USER_MODEL)),
                ('silenciado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grupos_erro_silenciados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'adm_grupo_erro_producao',
                'ordering': ('-ultima_ocorrencia',),
            },
        ),
        migrations.CreateModel(
            name='EventoErroProducao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(blank=True, db_index=True, max_length=80)),
                ('trace_id', models.CharField(blank=True, db_index=True, max_length=80)),
                ('metodo_http', models.CharField(blank=True, max_length=10)),
                ('caminho', models.CharField(blank=True, max_length=255)),
                ('status_http', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('tempo_resposta_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('payload_sanitizado', models.JSONField(blank=True, null=True)),
                ('stack_trace', models.TextField(blank=True)),
                ('versao_app', models.CharField(blank=True, max_length=50)),
                ('pod', models.CharField(blank=True, max_length=80)),
                ('deploy_recente', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='modulo_adm.grupoerroproducao')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_erro_producao', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'adm_evento_erro_producao',
                'ordering': ('-criado_em',),
            },
        ),
        migrations.AddIndex(
            model_name='grupoerroproducao',
            index=models.Index(fields=['-ultima_ocorrencia'], name='adm_grupo_e_ultima__81f987_idx'),
        ),
        migrations.AddIndex(
            model_name='grupoerroproducao',
            index=models.Index(fields=['status', '-ultima_ocorrencia'], name='adm_grupo_e_status_b00323_idx'),
        ),
        migrations.AddIndex(
            model_name='grupoerroproducao',
            index=models.Index(fields=['severidade'], name='adm_grupo_e_severid_25697b_idx'),
        ),
        migrations.AddIndex(
            model_name='grupoerroproducao',
            index=models.Index(fields=['ambiente', '-ultima_ocorrencia'], name='adm_grupo_e_ambient_420446_idx'),
        ),
        migrations.AddIndex(
            model_name='eventoerroproducao',
            index=models.Index(fields=['grupo', '-criado_em'], name='adm_evento__grupo_i_6a60a8_idx'),
        ),
        migrations.AddIndex(
            model_name='eventoerroproducao',
            index=models.Index(fields=['request_id'], name='adm_evento__request_6c5219_idx'),
        ),
    ]
