# Generated by Django 4.2.29 on 2026-05-16 20:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('modulo_adm', '0004_production_health'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoSeguranca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('login_falha', 'Falha de login'), ('login_lockout', 'Login bloqueado temporariamente'), ('rate_limit', 'Limite de requisições excedido'), ('honeypot', 'Honeypot acionado (bot)'), ('user_agent_suspeito', 'User-Agent suspeito'), ('ip_bloqueado', 'IP bloqueado'), ('4xx_anomalo', 'Padrão anômalo de 4xx'), ('cliente_chave_invalida', 'Tentativa inválida no portal do cliente'), ('recuperacao_abuso', 'Abuso no formulário de recuperação')], db_index=True, max_length=40)),
                ('severidade', models.CharField(choices=[('info', 'Informativo'), ('warning', 'Atenção'), ('critical', 'Crítico')], default='warning', max_length=10)),
                ('ip', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('alvo', models.CharField(blank=True, db_index=True, max_length=255)),
                ('endpoint', models.CharField(blank=True, max_length=255)),
                ('metadados', models.JSONField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_seguranca', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'adm_evento_seguranca',
                'ordering': ('-criado_em',),
                'indexes': [models.Index(fields=['categoria', '-criado_em'], name='adm_evento__categor_dc124b_idx'), models.Index(fields=['ip', '-criado_em'], name='adm_evento__ip_814638_idx')],
            },
        ),
    ]
