# Generated by Django 4.2.29 on 2026-05-24 23:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modulo_oficina', '0006_oficina_limites_override'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssinaturaOficina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pendente', 'Aguardando pagamento'), ('ativa', 'Ativa'), ('vencida', 'Vencida'), ('cancelada', 'Cancelada')], default='pendente', max_length=15)),
                ('inicio_em', models.DateTimeField(blank=True, null=True)),
                ('expira_em', models.DateTimeField(blank=True, null=True)),
                ('cancelada_em', models.DateTimeField(blank=True, null=True)),
                ('ultimo_pagamento_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('oficina', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assinatura', to='modulo_oficina.oficina')),
            ],
            options={
                'verbose_name': 'Assinatura de oficina',
                'verbose_name_plural': 'Assinaturas de oficinas',
                'db_table': 'pag_assinatura_oficina',
            },
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('tipo', models.CharField(choices=[('assinatura', 'Assinatura SaaS'), ('os', 'Ordem de Serviço')], db_index=True, max_length=15)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('falha', 'Falha'), ('expirado', 'Expirado'), ('cancelado', 'Cancelado')], default='pendente', max_length=15)),
                ('metodo_escolhido', models.CharField(blank=True, choices=[('PIX', 'PIX'), ('CARD', 'Cartão de crédito'), ('BOLETO', 'Boleto')], max_length=10)),
                ('valor_centavos', models.PositiveIntegerField()),
                ('descricao', models.CharField(blank=True, max_length=200)),
                ('abacatepay_id', models.CharField(blank=True, db_index=True, help_text='ID da cobrança no AbacatePay (ex.: bill_abc123).', max_length=64)),
                ('abacatepay_url', models.URLField(blank=True, help_text='URL hospedada do checkout AbacatePay.', max_length=500)),
                ('expira_em', models.DateTimeField(blank=True, null=True)),
                ('pago_em', models.DateTimeField(blank=True, null=True)),
                ('metadados', models.JSONField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('assinatura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagamentos', to='modulo_pagamentos.assinaturaoficina')),
                ('cliente', models.ForeignKey(blank=True, help_text="Cliente final que paga (preenchido só em tipo='os').", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagamentos', to='modulo_oficina.cliente')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagamentos_criados', to=settings.AUTH_USER_MODEL)),
                ('oficina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos', to='modulo_oficina.oficina')),
                ('ordem_servico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagamentos', to='modulo_oficina.ordemservico')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'db_table': 'pag_pagamento',
                'ordering': ('-criado_em',),
            },
        ),
        migrations.CreateModel(
            name='PlanoSaaS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.SlugField(max_length=40, unique=True)),
                ('nome', models.CharField(max_length=80)),
                ('descricao', models.TextField(blank=True)),
                ('preco_centavos', models.PositiveIntegerField(help_text='Preço mensal em centavos. R$ 199,00 = 19900.')),
                ('limite_usuarios', models.PositiveIntegerField(default=0, help_text='0 = sem limite específico (cai no default global).')),
                ('limite_os_mensal', models.PositiveIntegerField(default=0, help_text='0 = sem limite específico (cai no default global).')),
                ('destaque', models.BooleanField(default=False, help_text="Marca como 'Recomendado' na UI de seleção.")),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.PositiveSmallIntegerField(default=0, help_text='Ordem de exibição (menor aparece primeiro).')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plano SaaS',
                'verbose_name_plural': 'Planos SaaS',
                'db_table': 'pag_plano_saas',
                'ordering': ('ordem', 'preco_centavos', 'codigo'),
            },
        ),
        migrations.CreateModel(
            name='EventoPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('criado', 'Pagamento criado'), ('checkout_gerado', 'Checkout AbacatePay gerado'), ('webhook_recebido', 'Webhook recebido'), ('pago', 'Pagamento confirmado'), ('falha', 'Falha'), ('expirado', 'Expirado'), ('cancelado', 'Cancelado'), ('simulado', 'Simulação manual (dev)')], max_length=20)),
                ('descricao', models.CharField(blank=True, max_length=200)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('pagamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='modulo_pagamentos.pagamento')),
            ],
            options={
                'verbose_name': 'Evento de pagamento',
                'verbose_name_plural': 'Eventos de pagamento',
                'db_table': 'pag_evento_pagamento',
                'ordering': ('-criado_em',),
            },
        ),
        migrations.AddField(
            model_name='assinaturaoficina',
            name='plano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assinaturas', to='modulo_pagamentos.planosaas'),
        ),
        migrations.CreateModel(
            name='WebhookAbacatePay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=128, unique=True)),
                ('evento', models.CharField(db_index=True, max_length=80)),
                ('payload', models.JSONField()),
                ('assinatura_valida', models.BooleanField(default=False)),
                ('processado', models.BooleanField(default=False)),
                ('processado_em', models.DateTimeField(blank=True, null=True)),
                ('erro', models.TextField(blank=True)),
                ('recebido_em', models.DateTimeField(auto_now_add=True)),
                ('pagamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhooks', to='modulo_pagamentos.pagamento')),
            ],
            options={
                'verbose_name': 'Webhook AbacatePay',
                'verbose_name_plural': 'Webhooks AbacatePay',
                'db_table': 'pag_webhook_abacatepay',
                'ordering': ('-recebido_em',),
                'indexes': [models.Index(fields=['-recebido_em'], name='pag_webhook_recebid_d3e327_idx'), models.Index(fields=['processado', '-recebido_em'], name='pag_webhook_process_d3e0e4_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='pagamento',
            index=models.Index(fields=['status', '-criado_em'], name='pag_pagamen_status_69bba1_idx'),
        ),
        migrations.AddIndex(
            model_name='pagamento',
            index=models.Index(fields=['tipo', 'status'], name='pag_pagamen_tipo_dd4ec6_idx'),
        ),
        migrations.AddIndex(
            model_name='pagamento',
            index=models.Index(fields=['oficina', '-criado_em'], name='pag_pagamen_oficina_04425a_idx'),
        ),
        migrations.AddIndex(
            model_name='pagamento',
            index=models.Index(fields=['abacatepay_id'], name='pag_pagamen_abacate_998cb8_idx'),
        ),
        migrations.AddIndex(
            model_name='eventopagamento',
            index=models.Index(fields=['pagamento', '-criado_em'], name='pag_evento__pagamen_c0c54e_idx'),
        ),
        migrations.AddIndex(
            model_name='assinaturaoficina',
            index=models.Index(fields=['status', 'expira_em'], name='pag_assinat_status_96dcd9_idx'),
        ),
    ]
