# Generated by Django 4.2.29 on 2026-05-15 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('modulo_oficina', '0003_manutencaopreventiva'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=160)),
                ('descricao', models.TextField()),
                ('categoria', models.CharField(choices=[('tecnico', 'Técnico / falha do sistema'), ('financeiro', 'Financeiro / cobrança'), ('acesso', 'Acesso / credenciais'), ('duvida', 'Dúvida geral'), ('sugestao', 'Sugestão de melhoria'), ('outro', 'Outro')], default='duvida', max_length=20)),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('em_atendimento', 'Em atendimento'), ('aguardando_usuario', 'Aguardando usuário'), ('resolvido', 'Resolvido'), ('fechado', 'Fechado')], default='aberto', max_length=20)),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('normal', 'Normal'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='normal', max_length=10)),
                ('origem', models.CharField(choices=[('oficina', 'Oficina'), ('cliente', 'Cliente final'), ('admin', 'Equipe administrativa')], default='oficina', max_length=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('fechado_em', models.DateTimeField(blank=True, null=True)),
                ('nao_lidas_usuario', models.PositiveIntegerField(default=0)),
                ('nao_lidas_admin', models.PositiveIntegerField(default=0)),
                ('atribuido_a', models.ForeignKey(blank=True, help_text='Usuário responsável pelo atendimento (staff/superuser).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_atribuidos', to=settings.AUTH_USER_MODEL)),
                ('autor_cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_abertos', to='modulo_oficina.cliente')),
                ('autor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_abertos', to=settings.AUTH_USER_MODEL)),
                ('oficina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='modulo_oficina.oficina')),
                ('os_relacionada', models.ForeignKey(blank=True, help_text='Quando o ticket é sobre uma OS específica.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='modulo_oficina.ordemservico')),
            ],
            options={
                'db_table': 'suporte_ticket',
                'ordering': ('-criado_em',),
            },
        ),
        migrations.CreateModel(
            name='MensagemTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eh_admin', models.BooleanField(default=False)),
                ('eh_interna', models.BooleanField(default=False, help_text='Quando True, a mensagem aparece apenas para o ADM (anotação interna). Útil para histórico de atendimento.')),
                ('conteudo', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('autor_cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensagens_suporte', to='modulo_oficina.cliente')),
                ('autor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensagens_suporte', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='modulo_suporte.ticket')),
            ],
            options={
                'db_table': 'suporte_mensagem_ticket',
                'ordering': ('criado_em',),
            },
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['status', '-criado_em'], name='suporte_tic_status_1ccafc_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['oficina', '-criado_em'], name='suporte_tic_oficina_1ca09e_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['autor_cliente', '-criado_em'], name='suporte_tic_autor_c_8fca9d_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['prioridade'], name='suporte_tic_priorid_9273ab_idx'),
        ),
        migrations.AddIndex(
            model_name='mensagemticket',
            index=models.Index(fields=['ticket', 'criado_em'], name='suporte_men_ticket__bdd813_idx'),
        ),
    ]
