# Generated by Django 4.2.29 on 2026-05-13 02:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modulo_oficina', '0002_funcionario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoAcessoOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=20, unique=True)),
                ('expira_em', models.DateTimeField()),
                ('tentativas', models.PositiveSmallIntegerField(default=0)),
                ('max_tentativas', models.PositiveSmallIntegerField(default=5)),
                ('revogado', models.BooleanField(default=False)),
                ('ultimo_uso_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('gerado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='codigos_acesso_gerados', to=settings.AUTH_USER_MODEL)),
                ('os', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codigos_acesso', to='modulo_oficina.ordemservico')),
            ],
            options={
                'db_table': 'codigo_acesso_os',
                'ordering': ('-criado_em',),
                'indexes': [models.Index(fields=['os', '-criado_em'], name='codigo_aces_os_id_81c33a_idx')],
            },
        ),
    ]
